title: Base de conocimiento
author: christian vega
description: sitio 

theme: just-the-docs
baseurl: /BC
url: "https://purrfectwarrior.github.io"
color_scheme: dark

aux_links:
  Soporte técnico:
    - https://marbelvega.github.io/
